### PR TITLE
Added mouse/touch events. Add most recent time to the top not bottom

### PR DESCRIPTION
**Pull request by gootik**

### CODE REVIEW

**Comment by maxflav** [comment]
Why do you want mouse events? I usually click on the window to make sure it has focus before starting the timer. Would you be okay with just adding touch events?

**Comment by gootik** [comment]
@maxflav fair enough. I'll remove the mouse event handler

**Comment by amokhtar** [comment]
Damn it @shezarkhani I just opened Github to do this

**Comment by amokhtar** [comment]
:+1: Though!

**Comment by gootik** [comment]
@maxflav updated PR

**Comment by amokhtar** [comment]
:+1:

**Pull request merged**
